Traceback (most recent call last):
  File "C:\Users\Javier\Dropbox\c_sldl_1_2_12\show_csv_results.py", line 5, in <module>
    from processdataf import process_data
  File "C:\Users\Javier\Dropbox\c_sldl_1_2_12\processdataf.py", line 1, in <module>
    import numpy as np
  File "C:\Users\Javier\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\numpy\__init__.py", line 144, in <module>
    from numpy.__config__ import show as show_config
  File "C:\Users\Javier\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\numpy\__config__.py", line 4, in <module>
    from numpy.core._multiarray_umath import (
  File "C:\Users\Javier\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\numpy\core\__init__.py", line 100, in <module>
    from . import _add_newdocs
  File "C:\Users\Javier\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\numpy\core\_add_newdocs.py", line 498, in <module>
    add_newdoc('numpy.core', 'nditer', ('reset',
  File "C:\Users\Javier\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\numpy\core\function_base.py", line 543, in add_newdoc
    new = getattr(__import__(place, globals(), {}, [obj]), obj)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 477, in _lock_unlock_module
  File "<frozen importlib._bootstrap>", line 374, in release
KeyboardInterrupt
^C